---
- name: Configure Crucible
  hosts: localhost
  tasks:
    - name: Download crucible from repository
      git:
        repo: 'https://github.com/redhat-partner-solutions/crucible.git'
        dest: /home/redhat/crucible