---
- name: Configure Crucible
  hosts: localhost
  tasks:
    - name: Download crucible from repository
      git:
        repo: 'https://github.com/redhat-partner-solutions/crucible.git'
        dest: /home/redhat/crucible

    - name: Copy inventory file
      copy:
        src: /home/redhat/slcm-crucible/inventory.yml
        dest: /home/redhat/crucible/inventory.yml

    - name: Copy the pull secret and rename it
      copy:
        src: /home/redhat/pull-secret
        dest: /home/redhat/crucible/pull-secret.txt

    - name: Install Ansible requirements
      shell:
        cmd: ansible-galaxy collection install -r /home/redhat/crucible/requirements.yml

    - name: Copy the inventory.vault.yml file
      copy:
        src: /home/redhat/slcm-crucible/inventory.vault.yml
        dest: /home/redhat/crucible/inventory.vault.yml